version: "3.9"

services:
  flask-app:
    container_name: flask-app
    build:
      dockerfile: ./OpenDrive
      context: .
    # ports:
    #   - "5000:5000"
    expose:
      - 5000
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"

  flask-db:
    container_name: flask-db
    hostname: flask-db.docker
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - flask-db-data:/var/lib/postgresql/data/pgdata

  worker:
    container_name: flask-worker
    build:
      dockerfile: Dockerfile.worker
      context: .
    env_file:
      - .env
    volumes:
      - "./:/app"

  flask-redis:
    container_name: redis-cache
    hostname: flask-redis.docker
    build:
      dockerfile: Dockerfile.redis
      context: .
    ports:
      - 6379:6379
    env_file:
      - .env
volumes:
  flask-db-data:
    name: flask-db-data
