version: "3.8"

services:
  flask-app:
    container_name: flask-app
    build:
      dockerfile: ./Dockerfile
      context: .
    # ports:
    #   - "5000:5000"
    expose:
      - 5000
    volumes:
      - ./:/app
    networks:
      - flask-network
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    depends_on:
      - flask-db
      - flask-redis
    restart: always
    # command: gunicorn -w 2 -b :5000 wsgi:flaskServer

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    networks:
      - flask-network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app

  flask-db:
    container_name: flask-db
    hostname: flask-db.docker
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - flask-network
    volumes:
      - flask-db-data:/var/lib/postgresql/data/pgdata

  worker:
    container_name: flask-worker
    build:
      dockerfile: Dockerfile.worker
      context: .
    env_file:
      - .env
    networks:
      - flask-network
    volumes:
      - "./:/app"

  flask-redis:
    container_name: flask-redis
    hostname: flask-redis.docker
    build:
      dockerfile: Dockerfile.redis
      context: .
    ports:
      - 6379:6379
    networks:
      - flask-network
    env_file:
      - .env
volumes:
  flask-db-data:
    name: flask-db-data

networks:
  flask-network:
