FROM python:3.9
WORKDIR /app

RUN apt-get -y update
RUN apt-get -y install gcc build-essential libpq-dev

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

ENV PYTHONIOENCODING=UTF-8
RUN pip3 install sqlalchemy_utils flask_dance flask_caching python-gitlab

COPY . /app

ENTRYPOINT ["python3", "-u" ,"manage.py", "run_worker"]

