version: "3.8"

services:
  flask-app:
    container_name: flask-app
    build:
      dockerfile: ./Dockerfile
      context: .
    # ports:
    #   - "5000:5000"
    expose:
      - 5000
    volumes:
      - ./:/app
    networks:
      - flask-network
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    depends_on:
      - flask-db
      - flask-redis
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - flask-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./OpenDrive/static:/var/www/html/static
      - ./OpenDrive/nginx/cert/conf:/etc/letsencrypt
      - ./OpenDrive/nginx/cert/www:/var/www/certbot
      - dhparam:/etc/ssl/certs
    depends_on:
      - flask-app
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./OpenDrive/nginx/cert/conf:/etc/letsencrypt
      - ./OpenDrive/nginx/cert/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # --force-renewal
  flask-db:
    container_name: flask-db
    hostname: flask-db.docker
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - flask-network
    volumes:
      - flask-db-data:/var/lib/postgresql/data/pgdata

  worker:
    container_name: flask-worker
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.worker
      context: .
    env_file:
      - .env
    networks:
      - flask-network
    volumes:
      - "./:/app"

  flask-redis:
    container_name: flask-redis
    hostname: flask-redis.docker
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.redis
      context: .
    ports:
      - 6379:6379
    networks:
      - flask-network
    env_file:
      - .env
volumes:
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      device: /etc/letsencrypt
      o: bind
  certbot-var:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/letsencrypt
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/dev/app/dhparam
      o: bind
  flask-db-data:
    name: flask-db-data

networks:
  flask-network:
