version: "3"

services:
  flask-app:
    container_name: flask-app
    build:
      dockerfile: Dockerfile.flask
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - .env

  flask-db:
    container_name: flask-db
    hostname: flask-db.docker
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    # - flask-db-data:/var/lib/postgresql/data/pgdata

  flask-redis:
    container_name: redis-cache
    build:
      dockerfile: Dockerfile.redis
      context: .
    ports:
      - 6379:6379
    env_file:
      - .env
# volumes:
#   flask-db-data:
#     name: flask-db-data
