"""empty message

Revision ID: 727412136ec6
Revises: c6b04646f58e
Create Date: 2021-05-25 13:40:23.647492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727412136ec6'
down_revision = 'c6b04646f58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
