"""empty message

Revision ID: 9f82589bd4ec
Revises: f788837d2298
Create Date: 2021-06-23 18:54:15.965357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f82589bd4ec'
down_revision = 'f788837d2298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('files', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
