"""empty message

Revision ID: b2381d05d435
Revises: c7d5bea8e7e6
Create Date: 2021-06-24 09:08:44.071417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2381d05d435'
down_revision = 'c7d5bea8e7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('size', sa.Integer(), nullable=True))
    op.execute("UPDATE files SET size = 0")
    op.alter_column('files', 'size', nullable=False)
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('files', 'size')
    # ### end Alembic commands ###
