"""empty message

Revision ID: c6b04646f58e
Revises: 209cf656bb99
Create Date: 2021-05-22 18:59:01.911105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b04646f58e'
down_revision = '209cf656bb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwords', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_index('ix_passwords_email', table_name='passwords')
    op.create_index(op.f('ix_passwords_username'), 'passwords', ['username'], unique=False)
    op.drop_column('passwords', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwords', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_passwords_username'), table_name='passwords')
    op.create_index('ix_passwords_email', 'passwords', ['email'], unique=False)
    op.drop_column('passwords', 'username')
    # ### end Alembic commands ###
