"""empty message

Revision ID: c7d5bea8e7e6
Revises: 727412136ec6
Create Date: 2021-05-27 23:43:33.253782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d5bea8e7e6'
down_revision = '727412136ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_user_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_user_id_fkey', 'files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
