"""empty message

Revision ID: fca1eb7ab8bf
Revises: b2381d05d435
Create Date: 2021-06-25 11:54:33.884309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca1eb7ab8bf'
down_revision = 'b2381d05d435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('folder', sa.String(length=512), nullable=True))
    op.execute("UPDATE files SET folder = '/'")
    op.alter_column('files', 'folder', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'folder')
    # ### end Alembic commands ###
